# Generated by Django 4.1.4 on 2022-12-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_api_id', models.IntegerField()),
                ('artist_name', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
