# Generated by Django 4.1.4 on 2022-12-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_alter_artist_artist_api_id_alter_artist_upvotes'),
        ('favorites', '0002_alter_favorite_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.artist'),
        ),
    ]
